-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgInxOyMcoCz4QIKOp
+K5XBVhidOXSWJgqUjGT2kPSNVWgCgYIKoZIzj0DAQehRANCAAQEk4QbWf/TYhj7
SO69MTAejuAXoT+iNtpJKiwRD8z3CfG3d5qSNXJ9DjbHhK4eQhUlozWnDdX96VTx
Wczm3aS9
-----END PRIVATE KEY-----